server:
  port: 6636
spring:
  sapjco:
    enabled: true
  application:
    name: sakura_pt
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sakuradb
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: NON_NULL
    # 常规默认,枚举类SerializationFeature中的枚举属性为key，值为boolean设置jackson序列化特性,具体key请看SerializationFeature源码
    serialization:
      # WRITE_DATES_AS_TIMESTAMPS: true # 返回的java.util.date转换成timestamp
      FAIL_ON_EMPTY_BEANS: true # 对象为空时是否报错，默认true
  mvc:
    async:
      request-timeout: 15000
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    cache-enabled: false
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: simple
    default-statement-timeout: 25000
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: oracle
  page-size-zero: true
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  client:
    config:
      default: # 服务名，填写 default 为所有服务，或者指定某服务，例如：annoroad-beta
        connectTimeout: 10000 # 连接超时，10秒
        readTimeout: 10000 # 读取超时，20秒
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: false
ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  eureka:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
hystrix:
  command:
    default:
      circuitBreaker:
        # 当在配置时间窗口内达到此数量的失败后，进行短路。默认20个
        requestVolumeThreshold: 1
        # 触发短路的时间值，当该值设为5000时，则当触发 circuit break 后的5000毫秒内都会拒绝request
        # 也就是5000毫秒后才会关闭circuit。默认5000
        sleepWindowInMilliseconds: 15000
        # 强制打开熔断器，如果打开这个开关，那么拒绝所有request，默认false
        forceOpen: false
        # 强制关闭熔断器 如果这个开关打开，circuit将一直关闭且忽略，默认false
        forceClosed: false
      execution:
        isolation:
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 5000
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: health,info
